# Generated by Django 2.2.4 on 2019-08-17 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nconst', models.IntegerField(db_index=True)),
                ('primary_name', models.CharField(max_length=105)),
                ('birth_year', models.IntegerField(null=True)),
                ('death_year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.IntegerField(db_index=True)),
                ('title_type', models.CharField(max_length=32)),
                ('primary_title', models.CharField(max_length=512)),
                ('original_title', models.CharField(max_length=512)),
                ('is_adult', models.BooleanField(default=False)),
                ('start_year', models.IntegerField(null=True)),
                ('end_year', models.IntegerField(null=True)),
                ('runtime_minutes', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tconst', models.CharField(max_length=16)),
                ('season_number', models.IntegerField(null=True)),
                ('episode_number', models.IntegerField(null=True)),
                ('episode_title',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_in',
                                   to='imdb.Title')),
                ('series_title',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes_of',
                                   to='imdb.Title')),
            ],
        ),
        migrations.CreateModel(
            name='TitleRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField()),
                ('num_votes', models.IntegerField()),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='imdb.Title')),
            ],
        ),
        migrations.CreateModel(
            name='TitleGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Genre')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Title')),
            ],
        ),
        migrations.CreateModel(
            name='TitleCrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('characters', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Profession')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.CrewMember')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Title')),
            ],
        ),
        migrations.AddField(
            model_name='title',
            name='crew',
            field=models.ManyToManyField(related_name='titles', through='imdb.TitleCrew', to='imdb.CrewMember'),
        ),
        migrations.AddField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(related_name='titles', through='imdb.TitleGenre', to='imdb.Genre'),
        ),
        migrations.AddField(
            model_name='title',
            name='episodes',
            field=models.ManyToManyField(through='imdb.TitleEpisode', to='imdb.Title'),
        ),
        migrations.CreateModel(
            name='CrewMemberProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.CrewMember')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Profession')),
            ],
        ),
        migrations.AddField(
            model_name='crewmember',
            name='professions',
            field=models.ManyToManyField(related_name='crew_members', through='imdb.CrewMemberProfession', to='imdb.Profession'),
        ),
        migrations.CreateModel(
            name='AlternativeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('alternative_title', models.CharField(max_length=512)),
                ('region', models.CharField(max_length=2)),
                ('language', models.CharField(max_length=2)),
                ('types', models.CharField(max_length=16)),
                ('attributes', models.CharField(max_length=16)),
                ('is_original_title', models.BooleanField(default=False)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_titles', to='imdb.Title')),
            ],
        ),
    ]
