# Generated by Django 2.2.4 on 2019-08-24 14:29
import csv
import os

import progressbar
from django.conf import settings
from django.db import migrations


DB_BATCH_SIZE = 500000


def populate_ratings(apps, *args, **kwargs):
    print("Populating title ratings")
    Title = apps.get_model('imdb', 'Title')
    TitleRating = apps.get_model('imdb', 'TitleRating')
    titles_by_tconst = {t.tconst: t for t in Title.objects.all()}
    with open(os.path.join(settings.IMDB_DATASET_LOCATION, 'title.ratings.tsv')) as f:
        reader = csv.DictReader(f, delimiter='\t')
        bar = progressbar.progressbar(reader)
        title_ratings = []
        for row in bar:
            tconst = int(row['tconst'].strip('tt'))
            title = titles_by_tconst[tconst]
            rating = TitleRating(title=title, average_rating=row['averageRating'], num_votes=row['numVotes'])
            title_ratings.append(rating)
        TitleRating.objects.bulk_create(title_ratings)


def truncate_ratings(apps, *args, **kwargs):
    TitleRating = apps.get_model('imdb', 'TitleRating')
    TitleRating.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0006_populate_episodes'),
    ]

    operations = [
        migrations.RunPython(populate_ratings, truncate_ratings)
    ]
