# Generated by Django 2.2.8 on 2019-12-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0008_watchedtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='is_adult',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterIndexTogether(
            name='title',
            index_together={('start_year', 'id')},
        ),
    ]
